### ISSUE TITLE
Jest failing

### ISSUE THREAD

**Issue by hamidfzm** [react-native-community/react-native-safe-area-view#108]
# Bug

Jest is failing even if I put following ignore patterns for jest:
```json
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native)/)"
    ]
```

```bash
$ /home/hamidfzm/Projects/test/node_modules/.bin/jest
 FAIL  __tests__/App-test.tsx
  ● Test suite failed to run

    /home/hamidfzm/Projects/test/node_modules/react-native-safe-area-view/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React, { Component } from 'react';
                                                                                                    ^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/react-native-paper/lib/commonjs/components/BottomNavigation.tsx:16:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.731s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment info

React native info output:

```bash
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 14.25 GB / 31.33 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-29 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 1.0.0
react-native-safe-area-context: 0.7.3

## Steps To Reproduce

yarn jest

**Comment by dmc1985** [comment]
@hamidfzm Did you ever find a solution for this? I'm having the exact same problem as you described.

**Comment by koutilyagurjikindi** [comment]
I am also facing the same problem

**Comment by brentvatne** [comment]
this library is deprecated, use react-native-safe-area-context instead :)
